language: php

env:
  - TRAVIS_NODE_VERSION="8.11.3"

sudo: required

php:
    - 7.2.16


services:
    - mysql

addons:
    chrome: stable

install:
    - nvm install $TRAVIS_NODE_VERSION
    - nvm alias default $TRAVIS_NODE_VERSION
    - mv .env.example .env
    - mysql -e 'create database vue_blog;'
    - composer self-update
    - composer install --no-interaction --prefer-dist --no-suggest
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run prod
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed --class=UsersTableSeeder

# before_script:
#     - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8000 http://localhost:8000 &
#     - php artisan serve &

# script:
#     - vendor/bin/phpunit
#     - php artisan dusk