language: php
env:
- TRAVIS_NODE_VERSION="8.11.3"
sudo: required
php:
- 7.2.16
services:
- mysql
addons:
  chrome: stable
  ssh_known_hosts: 101.201.71.119
install:
- nvm install $TRAVIS_NODE_VERSION
- nvm alias default $TRAVIS_NODE_VERSION
- mv .env.example .env
- mysql -e 'create database vue_blog;'
- composer self-update
- composer install --no-interaction --prefer-dist --no-suggest
- npm install -g cnpm --registry=https://registry.npm.taobao.org
- cnpm install
- npm run prod
- php artisan key:generate
- php artisan migrate
- php artisan db:seed --class=UsersTableSeeder
before_install:
- openssl aes-256-cbc -K $encrypted_da6fc65ed41b_key -iv $encrypted_da6fc65ed41b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh asahi@101.201.71.119 "~/autobash/my-blog"
